from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Callable
from urllib.parse import parse_qsl, urlparse

import pytest

from penage.core.actions import Action, ActionType
from penage.core.observations import Observation
from penage.core.state import State
from penage.core.tracer import JsonlTracer
from penage.core.validation_recorder import ValidationRecorder
from penage.llm.fake import FakeLLMClient
from penage.memory.store import MemoryStore
from penage.sandbox.fake_browser import FakeBrowser
from penage.specialists.base import SpecialistConfig
from penage.specialists.vulns.xss import XssSpecialist
from penage.validation.browser import DEFAULT_PROBE_EXPR, BrowserEvidenceValidator


Responder = Callable[[Action], Observation]


@dataclass
class FakeHttp:
    responder: Responder
    calls: list[Action] = field(default_factory=list)

    async def run(self, action: Action) -> Observation:
        self.calls.append(action)
        return self.responder(action)

    async def aclose(self) -> None:
        return None


def _reflected_param_value(action: Action, parameter: str) -> str:
    params = action.params
    method = str(params.get("method") or "GET").upper()
    if method == "GET":
        q = dict(parse_qsl(urlparse(str(params["url"])).query, keep_blank_values=True))
        return q.get(parameter, "")
    data = params.get("data") or {}
    return str(data.get(parameter, ""))


def _vulnerable_echo(parameter: str) -> Responder:
    """Echo the parameter value verbatim inside an attribute position."""

    def respond(action: Action) -> Observation:
        injected = _reflected_param_value(action, parameter)
        body = (
            "<html><body><form method=\"POST\" action=\"/search\">"
            f"<input type=\"text\" name=\"{parameter}\" value=\"{injected}\" />"
            "</form></body></html>"
        )
        return Observation(
            ok=True,
            data={
                "status_code": 200,
                "url": action.params.get("url"),
                "headers": {"content-type": "text/html"},
                "text_full": body,
                "text_excerpt": body,
            },
        )

    return respond


def _browser_validator_with_execution_for(probe_urls: set[str]) -> BrowserEvidenceValidator:
    """Build a BrowserEvidenceValidator whose FakeBrowser signals execution
    for any probe URL in ``probe_urls`` (empty DOM + non-empty marker array)."""
    dom_responses: dict[str, str] = {}
    for url in probe_urls:
        # Payload must appear in DOM for the validator to advance past the
        # reflection check. We use a generic substitution that will match any
        # payload the specialist chooses — see _browser_validator_any_execution.
        dom_responses[url] = ""
    js_responses = {
        DEFAULT_PROBE_EXPR: json.dumps(
            [{"type": "alert", "message": "xss"}]
        ),
    }
    return BrowserEvidenceValidator(
        FakeBrowser(dom_responses=dom_responses, js_responses=js_responses)
    )


class _PayloadEchoBrowser:
    """A FakeBrowser-like object that always reflects the payload in the DOM.

    Needed because real XSS payloads are generated by PayloadMutator and not
    known ahead of time — so we can't pre-populate ``dom_responses`` per URL.
    Instead this browser echoes the ``browser_payload`` back inside an HTML
    wrapper so the validator's "payload in dom" check always passes.
    """

    def __init__(self, *, executed: bool) -> None:
        self._executed = executed
        self._current_payload: str = ""
        self._current_url: str | None = None
        self.navigations: list[str] = []
        self.js_calls: list[str] = []
        self.closed = False

    async def navigate(self, url: str) -> None:
        self.navigations.append(url)
        self._current_url = url

    async def get_dom(self) -> str:
        return f"<html><body>{self._current_payload}</body></html>"

    async def eval_js(self, expr: str) -> Any:
        self.js_calls.append(expr)
        if self._executed:
            return json.dumps([{"type": "alert", "message": "xss"}])
        return "[]"

    async def aclose(self) -> None:
        self.closed = True


class _PayloadAwareBrowserValidator(BrowserEvidenceValidator):
    """Thin wrapper that primes the fake browser's 'payload' per call so the
    DOM-reflection gate always matches the specialist's payload."""

    def __init__(self, browser: _PayloadEchoBrowser) -> None:
        super().__init__(browser)
        self._echo = browser

    async def validate(self, *, action, obs, state):
        self._echo._current_payload = str((action.params or {}).get("browser_payload") or "")
        return await super().validate(action=action, obs=obs, state=state)


def _state_with_form(base_url: str, parameter: str) -> State:
    st = State(base_url=base_url)
    st.last_http_url = base_url
    st.forms_by_url = {
        base_url: [
            {
                "action": base_url,
                "method": "POST",
                "inputs": [{"name": parameter, "type": "text"}],
            }
        ]
    }
    return st


def _recorder(tmp_path) -> ValidationRecorder:
    tracer = JsonlTracer(tmp_path / "trace.jsonl", episode_id="unit-xss")
    return ValidationRecorder(tracer=tracer, validator=None)


@pytest.mark.asyncio
async def test_xss_specialist_full_five_phase_flow_yields_verified_finding(tmp_path):
    base_url = "http://localhost/search"
    parameter = "q"

    http_tool = FakeHttp(responder=_vulnerable_echo(parameter))
    llm = FakeLLMClient(fixed_text=json.dumps([
        '" autofocus onfocus=alert(1) x="',
        '"><img src=x onerror=alert(1)>',
    ]))
    memory = MemoryStore(":memory:")

    echo = _PayloadEchoBrowser(executed=True)
    validator = _PayloadAwareBrowserValidator(echo)
    recorder = _recorder(tmp_path)

    specialist = XssSpecialist(
        http_tool=http_tool,
        llm_client=llm,
        memory=memory,
        browser_validator=validator,
        validation_recorder=recorder,
        max_http_budget=50,
    )

    state = _state_with_form(base_url, parameter)
    candidates = await specialist.propose_async(state, config=SpecialistConfig(max_candidates=3))

    assert len(candidates) == 1
    cand = candidates[0]
    assert cand.source == "xss"
    assert cand.action.type == ActionType.NOTE
    finding = cand.metadata["evidence"]
    assert finding["verified"] is True
    assert finding["parameter"] == parameter
    assert finding["context"] == "attr_quoted"

    browser_evidence = finding["evidence"]["browser"]
    assert browser_evidence["execution_markers"]
    assert browser_evidence["execution_markers"][0]["type"] == "alert"
    assert finding["evidence"]["validation_level"] == "validated"

    # Validator was actually consulted.
    assert echo.navigations, "browser validator should navigate at least once"

    # Recorder populated state.last_validation through the gate-path.
    assert state.last_validation is not None
    assert state.last_validation["level"] == "validated"

    # Budget accounting bumped on episode state.
    assert state.http_requests_used == len(http_tool.calls)
    assert state.tool_calls_http == len(http_tool.calls)

    # Second call after a verified finding is a no-op (short-circuit).
    pre_calls = len(http_tool.calls)
    more = await specialist.propose_async(state, config=SpecialistConfig(max_candidates=3))
    assert more and more[0].metadata["evidence"]["verified"] is True
    assert len(http_tool.calls) == pre_calls


@pytest.mark.asyncio
async def test_xss_specialist_falls_back_to_unverified_without_browser_validator():
    base_url = "http://localhost/search"
    parameter = "q"

    http_tool = FakeHttp(responder=_vulnerable_echo(parameter))
    llm = FakeLLMClient(fixed_text=json.dumps(['" onfocus=alert(1) x="']))
    memory = MemoryStore(":memory:")

    specialist = XssSpecialist(
        http_tool=http_tool,
        llm_client=llm,
        memory=memory,
        browser_validator=None,  # ablation: --no-browser-verification
        validation_recorder=None,
        max_http_budget=40,
    )

    state = _state_with_form(base_url, parameter)
    candidates = await specialist.propose_async(state, config=SpecialistConfig(max_candidates=2))

    assert candidates, "fallback should emit an unverified reflection finding"
    finding = candidates[0].metadata["evidence"]
    assert finding["verified"] is False
    assert finding["kind"] == "xss_unverified_reflection"


@pytest.mark.asyncio
async def test_xss_specialist_reports_evidence_only_when_browser_reflects_without_execution(
    tmp_path,
):
    base_url = "http://localhost/search"
    parameter = "q"

    http_tool = FakeHttp(responder=_vulnerable_echo(parameter))
    llm = FakeLLMClient(fixed_text=json.dumps(['" onfocus=alert(1) x="']))
    memory = MemoryStore(":memory:")

    echo = _PayloadEchoBrowser(executed=False)  # DOM reflection but no JS execution
    validator = _PayloadAwareBrowserValidator(echo)
    recorder = _recorder(tmp_path)

    specialist = XssSpecialist(
        http_tool=http_tool,
        llm_client=llm,
        memory=memory,
        browser_validator=validator,
        validation_recorder=recorder,
        max_http_budget=40,
    )

    state = _state_with_form(base_url, parameter)
    candidates = await specialist.propose_async(state, config=SpecialistConfig(max_candidates=2))

    assert candidates
    finding = candidates[0].metadata["evidence"]
    assert finding["verified"] is False
    assert finding["evidence"]["validation_level"] == "evidence"
    assert state.last_validation is not None
    assert state.last_validation["level"] == "evidence"


@pytest.mark.asyncio
async def test_xss_specialist_skips_targets_already_tried(tmp_path):
    base_url = "http://localhost/search"
    parameter = "q"

    http_tool = FakeHttp(responder=_vulnerable_echo(parameter))
    llm = FakeLLMClient(fixed_text=json.dumps(['" onfocus=alert(1) x="']))
    memory = MemoryStore(":memory:")

    echo = _PayloadEchoBrowser(executed=False)
    validator = _PayloadAwareBrowserValidator(echo)
    recorder = _recorder(tmp_path)

    specialist = XssSpecialist(
        http_tool=http_tool,
        llm_client=llm,
        memory=memory,
        browser_validator=validator,
        validation_recorder=recorder,
        max_http_budget=50,
    )

    state = _state_with_form(base_url, parameter)
    await specialist.propose_async(state, config=SpecialistConfig(max_candidates=2))

    # Memory records every probed payload. The deterministic attr_quoted
    # library places the onfocus+autofocus variant first.
    assert memory.was_tried(
        episode_id=specialist._episode_id(),
        host="localhost",
        parameter=parameter,
        payload='" onfocus=alert(1) autofocus x="',
    )


@pytest.mark.asyncio
async def test_xss_specialist_respects_http_budget():
    base_url = "http://localhost/search"
    parameter = "q"

    http_tool = FakeHttp(responder=_vulnerable_echo(parameter))
    llm = FakeLLMClient(fixed_text="")
    specialist = XssSpecialist(
        http_tool=http_tool,
        llm_client=llm,
        memory=None,
        browser_validator=None,
        validation_recorder=None,
        max_http_budget=4,  # below min_reserve_http default 8
    )
    state = _state_with_form(base_url, parameter)
    candidates = await specialist.propose_async(state, config=SpecialistConfig(max_candidates=2))

    assert candidates == []
    assert http_tool.calls == []


@pytest.mark.asyncio
async def test_xss_specialist_no_targets_returns_empty():
    http_tool = FakeHttp(responder=_vulnerable_echo("q"))
    specialist = XssSpecialist(
        http_tool=http_tool,
        llm_client=FakeLLMClient(fixed_text=""),
        memory=None,
        browser_validator=None,
        validation_recorder=None,
    )
    state = State(base_url="http://localhost/")
    candidates = await specialist.propose_async(state, config=SpecialistConfig())
    assert candidates == []
    assert http_tool.calls == []


@pytest.mark.asyncio
async def test_xss_specialist_writes_trace_events_for_each_phase(tmp_path):
    trace_path = tmp_path / "trace.jsonl"
    tracer = JsonlTracer(trace_path, episode_id="unit-xss")

    base_url = "http://localhost/search"
    parameter = "q"
    http_tool = FakeHttp(responder=_vulnerable_echo(parameter))
    llm = FakeLLMClient(fixed_text=json.dumps(['" onfocus=alert(1) x="']))

    echo = _PayloadEchoBrowser(executed=True)
    validator = _PayloadAwareBrowserValidator(echo)
    recorder = ValidationRecorder(tracer=tracer, validator=None)

    specialist = XssSpecialist(
        http_tool=http_tool,
        llm_client=llm,
        memory=MemoryStore(":memory:"),
        browser_validator=validator,
        validation_recorder=recorder,
        tracer=tracer,
    )

    state = _state_with_form(base_url, parameter)
    await specialist.propose_async(state, config=SpecialistConfig(max_candidates=2))

    events = [json.loads(line) for line in trace_path.read_text().splitlines() if line.strip()]
    phase_events = [e for e in events if e["event"] == "specialist_phase"]
    phases = sorted({e["payload"]["phase"] for e in phase_events})
    assert phases == [1, 2, 3, 4, 5]

    # Recorder emitted a validation event into the trace too.
    validation_events = [e for e in events if e["event"] == "validation"]
    assert validation_events, "recorder should write validation event to trace"
    assert validation_events[0]["payload"]["result"]["level"] == "validated"
